### ISSUE TITLE
SIgn-Up Page is Unresponsive

### ISSUE THREAD

**Issue by Bhavaj-Singla** [depanshu357/TrackIT-grp9#16]
The "Password" field must have a special character to work, but if we enter a password that does not satisfy this requirement, no error is shown and the page is unresponsive. 
Page is unresponsive when we enter any wrong information, no prompt is shown to rectify the error

**Comment by Babirrr** [comment]
This is a bug, as any functional website would show an error on typing an invalid password. The user will be confused if no prompt is shown.
