### ISSUE TITLE
Undesired outcome on refreshing page

### ISSUE THREAD

**Issue by Mohak-Singh-Rana** [depanshu357/TrackIT-grp9#17]
Refreshing on expenses, borrowing or analytics page directs the website to the home page, which is cumbersome for someone who reloads a page (suppose the analytics page) to look at the fresh analytics but is instead directed to a different page.

**Comment by depanshu357** [comment]
It' s just a property of reload page , not a issue

**Comment by Babirrr** [comment]
A user will reload a page wishing to see the updated data on that page itself. The user will find it annoying if he/she is repeatedly redirected to the home page. Reloading a page should show that page itself, hence it is a serious issue, which requires fixing.
