### ISSUE TITLE
Expense Status

### ISSUE THREAD

**Issue by Mohak-Singh-Rana** [depanshu357/TrackIT-grp9#18]
Shopkeepers can change the status of expenses from paid to unpaid which is a serious issue as shopkeepers can change the status of past expenses claiming false bills because we even do not have any receipts of the bills paid.

**Comment by depanshu357** [comment]
Well it's not a bug ,shopkeeper can change upaid to paid because if accidentally makes paid to unpaid by clicking the button , he can undo it by clicking the button again. And , the user is always informed if the borrowing are paid or not in his account

**Comment by Bhavaj-Singla** [comment]
There is no "History Log" of when the shopkeeper clicked the paid-unpaid button, so if a shopkeeper changes the status of a transaction from paid to unpaid in the future, the customer has no way of proving that the transaction was made earlier.
