### ISSUE TITLE
Allows addition of Impractical Transactions

### ISSUE THREAD

**Issue by Bhavaj-Singla** [depanshu357/TrackIT-grp9#21]
We can add an expense with a future date selected, which is not practical.
Also, on adding an expense for a very future date, the new expense is shown on the recent expenses block, but the new expense is not added in the graphs and analytics. 
The Website allows the addition of non-positive expenses which is meaningless.

**Comment by aryanmaurya383** [comment]
We have fixed the negative expenses part. The option of being able to enter data in future date is a feature and we will keep it
