### ISSUE TITLE
Security Issue

### ISSUE THREAD

**Issue by Mohak-Singh-Rana** [depanshu357/TrackIT-grp9#23]
The OTP is console logged whenever an OTP is requested to verify the user. This is a severe security issue for obvious reasons.
![WhatsApp Image 2023-04-11 at 02 04 14](https://user-images.githubusercontent.com/107363735/230993130-e79f70e8-70f6-4191-ad25-e049f6f5c1c1.jpeg)

**Comment by aryanmaurya383** [comment]
This is just for development purpose as you might not have new emails all the time and you just want to signup using dummy emails.
